baseurl: /code-manifesto
description: The Code Manifesto
permalink: pretty
title: The Code Manifesto
url: "https://greydnls/.github.io"

nav:
  - title: About
    url: about

rtl_languages:
  - arabic
  - hebrew